name: Supabase Keep-Alive

on:
  schedule:
    # Menjalankan workflow setiap Senin, Rabu, dan Jumat jam 7 pagi UTC
    - cron: '0 7 * * 1,3,5'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -X GET \
            "${{ secrets.SUPABASE_URL }}/rest/v1/users?select=id&limit=1" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
